# Generated by Django 4.1.7 on 2023-03-05 14:27

from django.db import migrations, models

import common.validators
import mainapp.models.customer


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=mainapp.models.customer.generate_uuid_for_author_avatar,
                        validators=[
                            common.validators.FileSizeValidator(1048576),
                            common.validators.FileExtensionValidator([".png", ".jpeg", ".jpg"]),
                        ],
                        verbose_name="Avatar",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
