# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# if we want ro exclude migrations and static
# exclude: ^[^/]*/migrations/[^/]*$|^static/.+$
exclude: ^src/static/.+$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-ast
    -   id: trailing-whitespace
    -   id: check-toml
    -   id: end-of-file-fixer

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
    -   id: add-trailing-comma

-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: pretty-format-yaml
        args:
        -   --autofix
        -   --preserve-quotes
        -   --indent=4

-   repo: https://github.com/python-poetry/poetry
    rev: 1.3.2
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]

-   repo: local
    hooks:
    -   id: black
        name: Format with Black
        entry: poetry run black
        language: system
        types: [python]

    -   id: autoflake
        name: autoflake
        entry: poetry run autoflake
        language: system
        types: [python]
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

    -   id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        args: ["--profile", "black"]

    -   id: flake8
        name: Check with Flake8
        entry: poetry run flake8
        language: system
        pass_filenames: false
        types: [python]
        args: [--count, .]

    -   id: django-check
        name: Django check
        entry: python src/manage.py check --deploy
        always_run: true
        pass_filenames: false
        language: system

    -   id: django-makemigrations
        name: Django makemigrations
        entry: python src/manage.py makemigrations --dry-run --check --no-input
        always_run: true
        pass_filenames: false
        language: system

    -   id: django-test
        name: Django test
        entry: docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from app
        always_run: true
        pass_filenames: false
        language: system
