version: "3"

services:
    app:
        build:
            context: .
        volumes:
        -   .:/src
        command: >
            sh -c "./wait-for-it.sh db:5432 &&  python manage.py test"
        environment:
        -   DB_HOST=db
        -   DB_NAME=app
        -   DB_USER=postgres
        -   DB_PASS=temppassword
        depends_on:
        -   db

    db:
        image: postgres:13-alpine
        environment:
        -   POSTGRES_DB=app
        -   POSTGRES_USER=postgres
        -   POSTGRES_PASSWORD=temppassword
        volumes:
        -   ./dbdatatest:/dbdata

volumes:
    src:
    dbdatatest:
