version: "3"

services:
    app:
        build:
            context: .
        ports:
        -   8001:8001
        volumes:
        -   .:/src
        command: >
            sh -c "./wait-for-it.sh db:5432 &&  python manage.py migrate && python manage.py collectstatic --no-input &&  gunicorn -c config/gunicornconfig.py"
        environment:
        -   DB_HOST=${DB_HOST}
        -   DB_NAME=${DB_NAME}
        -   DB_USER=${DB_USER}
        -   DB_PASS=${DB_PASS}
        -   DISABLE_SERVER_SIDE_CURSORS=${DISABLE_SERVER_SIDE_CURSORS}
        depends_on:
        -   db
        -   redis

    db:
        image: postgres:13-alpine
        environment:
        -   POSTGRES_DB=${POSTGRES_DB}
        -   POSTGRES_USER=${POSTGRES_USER}
        -   POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        -   PGDATA=${PGDATA}
        volumes:
        -   ./dbdata:/dbdata

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
        -   "5052:80"
        environment:
        -   PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        -   PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        volumes:
        -   pgadmindata:/var/lib/pgadmin

    redis:
        image: "redis:alpine"

    celery:
        build:
            context: .
        command: celery -A config worker -l info
        volumes:
        -   .:/src
        depends_on:
        -   db
        -   redis

    celery-beat:
        build:
            context: .
        command: celery -A config beat -l info
        volumes:
        -   .:/src
        depends_on:
        -   db
        -   redis

    celery-flower:
        build:
            context: .
        command: celery -A config flower
        ports:
        -   5555:5555
        volumes:
        -   .:/src
        depends_on:
        -   celery

volumes:
    src:
    dbdata:
    pgadmindata:
